apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - runner.yaml
secretGenerator:
  - name: gitlab-runner-gitlab-runner
    literals:
      - runner-registration-token="XXnFZJGfVhFeFLgVy-6P"
      - runner-token=""
